./demo icodegen/typecheck/test/in01
./demo icodegen/typecheck/test/in01a
./demo icodegen/typecheck/test/in01b
./demo icodegen/typecheck/test/in02
./demo icodegen/typecheck/test/in02a
./demo icodegen/typecheck/test/in02b
./demo icodegen/typecheck/test/in03
./demo icodegen/typecheck/test/in03a
./demo icodegen/typecheck/test/in04a
./demo icodegen/typecheck/test/in04b
./demo icodegen/typecheck/test/in05
./demo icodegen/typecheck/test/in05a
./demo icodegen/typecheck/test/in05b
./demo icodegen/typecheck/test/in06a
./demo icodegen/typecheck/test/in06b
./demo icodegen/typecheck/test/in06c
./demo icodegen/typecheck/test/in07
./demo icodegen/typecheck/test/in08
